void freefare_free_tags(FreefareTag *tags);
FreefareTag *freefare_get_tags(nfc_device *device);
enum freefare_tag_type freefare_get_tag_type(FreefareTag tag);
char *freefare_get_tag_uid(FreefareTag tag);
MifareDESFireKey mifare_desfire_3des_key_new(const uint8_t value[16]);
MifareDESFireKey mifare_desfire_3k3des_key_new(const uint8_t value[24]);
MifareDESFireKey mifare_desfire_aes_key_new(const uint8_t value[16]);
MifareDESFireAID mifare_desfire_aid_new(uint32_t aid);
int mifare_desfire_authenticate(FreefareTag tag, uint8_t key_no, MifareDESFireKey key);
int mifare_desfire_change_key(FreefareTag tag, uint8_t key_no, MifareDESFireKey new_key, MifareDESFireKey old_key);
int mifare_desfire_connect(FreefareTag tag);
int mifare_desfire_create_application_aes(FreefareTag tag, MifareDESFireAID aid, uint8_t settings, uint8_t key_no);
int mifare_desfire_create_std_data_file(FreefareTag tag, uint8_t file_no, uint8_t communication_settings, uint16_t access_rights, uint32_t file_size);
int mifare_desfire_delete_application(FreefareTag tag, MifareDESFireAID aid);
MifareDESFireKey mifare_desfire_des_key_new(const uint8_t value[8]);
int mifare_desfire_disconnect(FreefareTag tag);
int mifare_desfire_format_picc(FreefareTag tag);
int mifare_desfire_get_application_ids(FreefareTag tag, MifareDESFireAID *aids[], size_t *count);
void mifare_desfire_key_free(MifareDESFireKey key);
int mifare_desfire_select_application(FreefareTag tag, MifareDESFireAID aid);
int mifare_desfire_set_configuration(FreefareTag tag, _Bool disable_format, _Bool enable_random_uid);
int mifare_desfire_set_default_key(FreefareTag tag, MifareDESFireKey key);
int mifare_key_deriver_begin(MifareKeyDeriver deriver);
MifareDESFireKey mifare_key_deriver_end(MifareKeyDeriver deriver);
void mifare_key_deriver_free(MifareKeyDeriver state);
MifareKeyDeriver mifare_key_deriver_new_an10922(MifareDESFireKey master_key, MifareKeyType output_key_type);
int mifare_key_deriver_update_aid(MifareKeyDeriver deriver, MifareDESFireAID aid);
int mifare_key_deriver_update_uid(MifareKeyDeriver deriver, FreefareTag tag);
void nfc_close(nfc_device *pnd);
void nfc_exit(nfc_context *context) __attribute__((nonnull (1)));
void nfc_init(nfc_context **context) __attribute__((nonnull (1)));
size_t nfc_list_devices(nfc_context *context, nfc_connstring connstrings[], size_t connstrings_len) __attribute__((nonnull (1)));
nfc_device *nfc_open(nfc_context *context, const nfc_connstring connstring) __attribute__((nonnull (1)));
